Set-Location "C:\OneDrive\Jessica Ariadne Murphy\OneDrive\OneDrive Files\AppData Settings and Start Menu Configuration Auto Backup\Jessica Ariadne Murphy\Total War Warhammer III - Settings and Save Games Auto Backup"
cmd /c rmdir /s /q "advice_history"
cmd /c rmdir /s /q "auth"
cmd /c rmdir /s /q "battle_preferences"
cmd /c rmdir /s /q "custom_keys"
cmd /c rmdir /s /q "event_feed"
cmd /c rmdir /s /q "ingame_messaging"
cmd /c rmdir /s /q "maps"
cmd /c rmdir /s /q "replays"
cmd /c rmdir /s /q "resume"
cmd /c rmdir /s /q "saved_characters"
cmd /c rmdir /s /q "save_games"
cmd /c rmdir /s /q "screenshots"
cmd /c rmdir /s /q "scripts"

New-Item -ItemType Junction -Path "advice_history" -Target "D:\OneDrive\Mounted Drives\Samsung 990 PRO NVMe SSD\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\advice_history"
New-Item -ItemType Junction -Path "auth" -Target "D:\OneDrive\Mounted Drives\Samsung 990 PRO NVMe SSD\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\auth"
New-Item -ItemType Junction -Path "battle_preferences" -Target "D:\OneDrive\Mounted Drives\Samsung 990 PRO NVMe SSD\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\battle_preferences"
New-Item -ItemType Junction -Path "custom_keys" -Target "D:\OneDrive\Mounted Drives\Samsung 990 PRO NVMe SSD\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\custom_keys"
New-Item -ItemType Junction -Path "event_feed" -Target "D:\OneDrive\Mounted Drives\Samsung 990 PRO NVMe SSD\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\event_feed"
New-Item -ItemType Junction -Path "ingame_messaging" -Target "D:\OneDrive\Mounted Drives\Samsung 990 PRO NVMe SSD\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\ingame_messaging"
New-Item -ItemType Junction -Path "maps" -Target "D:\OneDrive\Mounted Drives\Samsung 990 PRO NVMe SSD\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\maps"

New-Item -ItemType Junction -Path "resume" -Target "D:\OneDrive\Mounted Drives\Samsung 990 PRO NVMe SSD\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\resume"
New-Item -ItemType Junction -Path "saved_characters" -Target "D:\OneDrive\Mounted Drives\Samsung 990 PRO NVMe SSD\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\saved_characters"
New-Item -ItemType Junction -Path "save_games" -Target "D:\OneDrive\Mounted Drives\Samsung 990 PRO NVMe SSD\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\save_games"
New-Item -ItemType Junction -Path "screenshots" -Target "D:\OneDrive\Mounted Drives\Samsung 990 PRO NVMe SSD\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\screenshots"

#Temp Files
New-Item -ItemType Junction -Path "crash_report"  -Target "G:\Scrap AppData\Warhammer3\crash_report"
New-Item -ItemType Junction -Path "logs" -Target "G:\Scrap AppData\Warhammer3\logs"
New-Item -ItemType Junction -Path "replays" -Target "G:\Scrap AppData\Warhammer3\replays"