<# PART ONE - TOTAL WAR: WARHAMMER III - DYNAMIC LINK SECTION #>
Set-Location "C:\Program Files\Steam\steamapps\common\"
cmd /c rmdir /s /q "Total War Warhammer III"
New-Item -ItemType Junction -Path "Total War Warhammer III" -Target "C:\Total War Warhammer III - Symbolic Link Storage\Total War Warhammer III - Game Folder"

Set-Location "C:\Total War Warhammer III - Symbolic Link Storage\Total War Warhammer III - Game Folder"
cmd /c rmdir /s /q "data"
New-Item -ItemType Junction -Path "data" -Target "C:\Total War Warhammer III - Symbolic Link Storage\Total War Warhammer III - Data Folder"

cmd /c rmdir /s /q "assembly_kit"
New-Item -ItemType Junction -Path "assembly_kit" -Target "C:\Total War Warhammer III - Symbolic Link Storage\Total War Warhammer III - Assembly Kit"

Set-Location "C:\Program Files\Steam\steamapps\workshop\content"
cmd /c rmdir /s /q "1142710"
New-Item -ItemType Junction -Path "1142710" -Target "C:\OneDrive\Jessica Ariadne Murphy\OneDrive\OneDrive Files\Total War Warhammer III - OneDrive Backups\Total War Warhammer III - Steam Workshop Mods"

Set-Location "C:\OneDrive\Jessica Ariadne Murphy\OneDrive\OneDrive Files\Total War Warhammer III - OneDrive Backups"
cmd /c rmdir /s /q "Total War Warhammer III - Game Folder"
New-Item -ItemType Junction -Path "Total War Warhammer III - Game Folder" -Target "C:\Total War Warhammer III - Symbolic Link Storage\Total War Warhammer III - Game Folder"
cmd /c rmdir /s /q "Total War Warhammer III - Scripting Projects"
New-Item -ItemType Junction -Path "Total War Warhammer III - Scripting Projects" -Target "C:\OneDrive\Jessica Ariadne Murphy\OneDrive\Documents\Total War Warhammer III - Scripting Projects"
				<# cmd /c rmdir /s /q "Total War Warhammer III - Settings and Save Games Auto Backup" #>
New-Item -ItemType Directory -Path "Total War Warhammer III - Settings and Save Games Auto Backup"
Set-Location "Total War Warhammer III - Settings and Save Games Auto Backup"

cmd /c rmdir /s /q "advice_history"
cmd /c rmdir /s /q "auth"
cmd /c rmdir /s /q "battle_preferences"
cmd /c rmdir /s /q "custom_keys"
cmd /c rmdir /s /q "ingame_messaging"
cmd /c rmdir /s /q "maps"
cmd /c rmdir /s /q "replays"
cmd /c rmdir /s /q "resume"
cmd /c rmdir /s /q "saved_characters"
cmd /c rmdir /s /q "save_games"
cmd /c rmdir /s /q "screenshots"

New-Item -ItemType Junction -Path "advice_history" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\advice_history"
New-Item -ItemType Junction -Path "auth" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\auth"
New-Item -ItemType Junction -Path "battle_preferences" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\battle_preferences"
New-Item -ItemType Junction -Path "custom_keys" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\custom_keys"
New-Item -ItemType Junction -Path "event_feed" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\event_feed"
New-Item -ItemType Junction -Path "ingame_messaging" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\ingame_messaging"
New-Item -ItemType Junction -Path "maps" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\maps"
New-Item -ItemType Junction -Path "replays" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\replays"
New-Item -ItemType Junction -Path "resume" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\resume"
New-Item -ItemType Junction -Path "saved_characters" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\saved_characters"
New-Item -ItemType Junction -Path "save_games" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\save_games"
New-Item -ItemType Junction -Path "screenshots" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\screenshots"
New-Item -ItemType Junction -Path "scripts" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\scripts"

<# PART TWO - AppData Settings and Start Menu Configuration Auto Backup #>
Set-Location "C:\OneDrive\Jessica Ariadne Murphy\OneDrive\OneDrive Files"
Set-Location "AppData Settings and Start Menu Configuration Auto Backup\Jessica Ariadne Murphy"
cmd /c rmdir /s /q "Total War Warhammer III - Settings and Save Games Auto Backup"
New-Item -ItemType Directory -Path "Total War Warhammer III - Settings and Save Games Auto Backup"
Set-Location "Total War Warhammer III - Settings and Save Games Auto Backup"

cmd /c rmdir /s /q "advice_history"
cmd /c rmdir /s /q "auth"
cmd /c rmdir /s /q "battle_preferences"
cmd /c rmdir /s /q "custom_keys"
cmd /c rmdir /s /q "ingame_messaging"
cmd /c rmdir /s /q "maps"
cmd /c rmdir /s /q "replays"
cmd /c rmdir /s /q "resume"
cmd /c rmdir /s /q "saved_characters"
cmd /c rmdir /s /q "save_games"
cmd /c rmdir /s /q "screenshots"

New-Item -ItemType Junction -Path "advice_history" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\advice_history"
New-Item -ItemType Junction -Path "auth" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\auth"
New-Item -ItemType Junction -Path "battle_preferences" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\battle_preferences"
New-Item -ItemType Junction -Path "custom_keys" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\custom_keys"
New-Item -ItemType Junction -Path "event_feed" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\event_feed"
New-Item -ItemType Junction -Path "ingame_messaging" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\ingame_messaging"
New-Item -ItemType Junction -Path "maps" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\maps"
New-Item -ItemType Junction -Path "replays" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\replays"
New-Item -ItemType Junction -Path "resume" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\resume"
New-Item -ItemType Junction -Path "saved_characters" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\saved_characters"
New-Item -ItemType Junction -Path "save_games" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\save_games"
New-Item -ItemType Junction -Path "screenshots" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\screenshots"
New-Item -ItemType Junction -Path "scripts" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\scripts"

<# PART THREE - TOTAL WAR: WARHAMMER III - RUNCHER AND RPFM CONFIGURATION DYNAMIC LINK SECTION #>
Set-Location "C:\OneDrive\Jessica Ariadne Murphy\OneDrive\OneDrive Files\Total War Warhammer III - OneDrive Backups"
cmd /c rmdir /s /q "Total War Warhammer III - Runcher And RPFM Configuration Auto Backup"
New-Item -ItemType Directory -Path "Total War Warhammer III - Runcher And RPFM Configuration Auto Backup"

Set-Location "Total War Warhammer III - Runcher And RPFM Configuration Auto Backup"
cmd /c rmdir /s /q "Runcher Settings Backup"
New-Item -ItemType Junction -Path "Runcher Settings Backup" -Target "C:\Users\Jessica Murphy\AppData\Roaming\FrodoWazEre\runcher"
cmd /c rmdir /s /q "RPFM Settings Backup"
New-Item -ItemType Directory -Path "RPFM Settings Backup"
Set-Location "RPFM Settings Backup"
New-Item -ItemType Directory -Path "config"
Set-Location "config"

# autosaves folder can become very large. Remove if needed.
New-Item -ItemType Junction -Path "autosaves" -Target "C:\Users\Jessica Murphy\AppData\Roaming\FrodoWazEre\rpfm\config\autosaves"
New-Item -ItemType Junction -Path "dependencies" -Target "C:\Users\Jessica Murphy\AppData\Roaming\FrodoWazEre\rpfm\config\dependencies"
New-Item -ItemType Junction -Path "error" -Target "C:\Users\Jessica Murphy\AppData\Roaming\FrodoWazEre\rpfm\config\error"
New-Item -ItemType Junction -Path "old_ak_files" -Target "C:\Users\Jessica Murphy\AppData\Roaming\FrodoWazEre\rpfm\config\old_ak_files"
New-Item -ItemType Junction -Path "schemas" -Target "C:\Users\Jessica Murphy\AppData\Roaming\FrodoWazEre\rpfm\config\schemas"
New-Item -ItemType Junction -Path "table_patches" -Target "C:\Users\Jessica Murphy\AppData\Roaming\FrodoWazEre\rpfm\config\table_patches"
New-Item -ItemType Junction -Path "translations_local" -Target "C:\Users\Jessica Murphy\AppData\Roaming\FrodoWazEre\rpfm\config\translations_local"

<# ONEDRIVE APPDATA COPY OF RUNCHER AND RPFM CONFIG #>
Set-Location "C:\OneDrive\Jessica Ariadne Murphy\OneDrive\OneDrive Files"
Set-Location "AppData Settings and Start Menu Configuration Auto Backup\Jessica Ariadne Murphy"
cmd /c rmdir /s /q "Total War Warhammer III - Runcher And RPFM Configuration Auto Backup"
New-Item -ItemType Directory -Path "Total War Warhammer III - Runcher And RPFM Configuration Auto Backup"
Set-Location "Total War Warhammer III - Runcher And RPFM Configuration Auto Backup"
cmd /c rmdir /s /q "Runcher Settings Backup"
New-Item -ItemType Junction -Path "Runcher Settings Backup" -Target "C:\Users\Jessica Murphy\AppData\Roaming\FrodoWazEre\runcher"
cmd /c rmdir /s /q "RPFM Settings Backup"
New-Item -ItemType Directory -Path "RPFM Settings Backup"
Set-Location "RPFM Settings Backup"
New-Item -ItemType Directory -Path "config"
Set-Location "config"

#autosaves folder can become very large. Remove if needed.
New-Item -ItemType Junction -Path "autosaves" -Target "C:\Users\Jessica Murphy\AppData\Roaming\FrodoWazEre\rpfm\config\autosaves"
New-Item -ItemType Junction -Path "dependencies" -Target "C:\Users\Jessica Murphy\AppData\Roaming\FrodoWazEre\rpfm\config\dependencies"
New-Item -ItemType Junction -Path "error" -Target "C:\Users\Jessica Murphy\AppData\Roaming\FrodoWazEre\rpfm\config\error"
New-Item -ItemType Junction -Path "old_ak_files" -Target "C:\Users\Jessica Murphy\AppData\Roaming\FrodoWazEre\rpfm\config\old_ak_files"
New-Item -ItemType Junction -Path "schemas" -Target "C:\Users\Jessica Murphy\AppData\Roaming\FrodoWazEre\rpfm\config\schemas"
New-Item -ItemType Junction -Path "table_patches" -Target "C:\Users\Jessica Murphy\AppData\Roaming\FrodoWazEre\rpfm\config\table_patches"
New-Item -ItemType Junction -Path "translations_local" -Target "C:\Users\Jessica Murphy\AppData\Roaming\FrodoWazEre\rpfm\config\translations_local"

<# PART FOUR - WINDOWS START MENU CONFIGURATION DYNAMIC LINK SECTION #>
Set-Location "C:\OneDrive\Jessica Ariadne Murphy\OneDrive\OneDrive Files"
Set-Location "AppData Settings and Start Menu Configuration Auto Backup\Jessica Ariadne Murphy"
New-Item -ItemType Directory -Path "Local"
Set-Location "Local"
New-Item -ItemType Directory -Path "Packages"
Set-Location "Packages"
New-Item -ItemType Directory -Path "Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy"
Set-Location "Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy"
cmd /c rmdir /s /q "LocalState"
New-Item -ItemType Junction -Path "LocalState" -Target "C:\Users\Jessica Murphy\AppData\Local\Packages\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\LocalState"
