Set-Location "C:\OneDrive\Jessica Ariadne Murphy\OneDrive\OneDrive Files\Total War Warhammer III - OneDrive Backups"
<# cmd /c rmdir /s /q "Total War Warhammer III - Settings and Save Games Auto Backup" #>
New-Item -ItemType Directory -Path "Total War Warhammer III - Settings and Save Games Auto Backup"
Set-Location "Total War Warhammer III - Settings and Save Games Auto Backup"

cmd /c rmdir /s /q "advice_history"
cmd /c rmdir /s /q "auth"
cmd /c rmdir /s /q "battle_preferences"
cmd /c rmdir /s /q "custom_keys"
cmd /c rmdir /s /q "ingame_messaging"
cmd /c rmdir /s /q "maps"
cmd /c rmdir /s /q "replays"
cmd /c rmdir /s /q "resume"
cmd /c rmdir /s /q "saved_characters"
cmd /c rmdir /s /q "save_games"
cmd /c rmdir /s /q "screenshots"

New-Item -ItemType Junction -Path "advice_history" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\advice_history"
New-Item -ItemType Junction -Path "auth" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\auth"
New-Item -ItemType Junction -Path "battle_preferences" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\battle_preferences"
New-Item -ItemType Junction -Path "custom_keys" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\custom_keys"
New-Item -ItemType Junction -Path "event_feed" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\event_feed"
New-Item -ItemType Junction -Path "ingame_messaging" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\ingame_messaging"
New-Item -ItemType Junction -Path "maps" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\maps"
New-Item -ItemType Junction -Path "replays" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\replays"
New-Item -ItemType Junction -Path "resume" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\resume"
New-Item -ItemType Junction -Path "saved_characters" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\saved_characters"
New-Item -ItemType Junction -Path "save_games" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\save_games"
New-Item -ItemType Junction -Path "screenshots" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\screenshots"
New-Item -ItemType Junction -Path "scripts" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\scripts"

<# PART TWO - AppData Settings and Start Menu Configuration Auto Backup #>
Set-Location "C:\OneDrive\Jessica Ariadne Murphy\OneDrive\OneDrive Files"
Set-Location "AppData Settings and Start Menu Configuration Auto Backup\Jessica Ariadne Murphy"
cmd /c rmdir /s /q "Total War Warhammer III - Settings and Save Games Auto Backup"
New-Item -ItemType Directory -Path "Total War Warhammer III - Settings and Save Games Auto Backup"
Set-Location "Total War Warhammer III - Settings and Save Games Auto Backup"

cmd /c rmdir /s /q "advice_history"
cmd /c rmdir /s /q "auth"
cmd /c rmdir /s /q "battle_preferences"
cmd /c rmdir /s /q "custom_keys"
cmd /c rmdir /s /q "ingame_messaging"
cmd /c rmdir /s /q "maps"
cmd /c rmdir /s /q "replays"
cmd /c rmdir /s /q "resume"
cmd /c rmdir /s /q "saved_characters"
cmd /c rmdir /s /q "save_games"
cmd /c rmdir /s /q "screenshots"

New-Item -ItemType Junction -Path "advice_history" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\advice_history"
New-Item -ItemType Junction -Path "auth" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\auth"
New-Item -ItemType Junction -Path "battle_preferences" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\battle_preferences"
New-Item -ItemType Junction -Path "custom_keys" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\custom_keys"
New-Item -ItemType Junction -Path "event_feed" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\event_feed"
New-Item -ItemType Junction -Path "ingame_messaging" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\ingame_messaging"
New-Item -ItemType Junction -Path "maps" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\maps"
New-Item -ItemType Junction -Path "replays" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\replays"
New-Item -ItemType Junction -Path "resume" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\resume"
New-Item -ItemType Junction -Path "saved_characters" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\saved_characters"
New-Item -ItemType Junction -Path "save_games" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\save_games"
New-Item -ItemType Junction -Path "screenshots" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\screenshots"
New-Item -ItemType Junction -Path "scripts" -Target "C:\Users\Jessica Murphy\AppData\Roaming\The Creative Assembly\Warhammer3\scripts"